# Generated by Django 5.2.8 on 2025-11-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Supplement', 'Supplement'), ('Equipment', 'Equipment'), ('Snacks', 'Snacks'), ('Protein', 'Protein'), ('Vitamins', 'Vitamins'), ('Organic', 'Organic'), ('Vegan', 'Vegan'), ('Others', 'Others')], max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('rating', models.CharField(choices=[('Not Good', 'Not Good'), ('Good', 'Good'), ('Super', 'Super'), ('Excellent', 'Excellent')], default='Good', max_length=10)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businessowner.businessowner')),
            ],
        ),
    ]
