# Generated by Django 5.2.8 on 2025-11-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
