# Generated by Django 5.2.8 on 2025-11-15 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('professional_email', models.EmailField(max_length=254, unique=True)),
                ('professional_phone', models.CharField(max_length=20)),
                ('social_media_account', models.CharField(blank=True, max_length=255, null=True)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
